import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { NetworkStatus } from '@/components/network-status';
import { PerformanceMonitor } from '@/components/performance-monitor';
import { Metadata } from 'next';
import Link from 'next/link';
import { 
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

export const metadata: Metadata = {
  title: 'FAQ - UPI QR Code Generator | freeupiqrgenerator.com',
  description: 'Find answers to frequently asked questions about our free UPI QR code generator. Learn about security, features, usage, and more.',
  keywords: 'UPI QR code FAQ, QR generator questions, UPI payment questions, QR code help',
  alternates: {
    canonical: '/faq',
  },
};

const faqData = [
  {
    question: "What is the difference between a UPI QR and a Bharat QR?",
    answer: "Our tool creates a standard UPI QR, perfect for accepting payments from any UPI app. Bharat QR is a specific type for businesses that also accepts cards. For most users, a UPI QR code is exactly what you need for digital payments."
  },
  {
    question: "Does this QR code expire?",
    answer: "No, UPI QR codes generated by our tool never expire. They remain functional as long as your UPI ID is active and your bank account is operational."
  },
  {
    question: "Is it safe to use this generator?",
    answer: "Absolutely! All QR code generation happens locally in your browser. We never store, access, or transmit your UPI details. Your information never leaves your device."
  },
  {
    question: "Can I create a QR code for a fixed amount?",
    answer: "Yes, you can specify a fixed amount in the amount field. This will pre-fill the amount when someone scans your QR code, making it perfect for specific products or services."
  },
  {
    question: "Do I need to create an account?",
    answer: "No! Unlike many other QR generators, we don't require any sign-up or account creation. Just visit our site and start generating QR codes immediately."
  },
  {
    question: "Are there any limits on QR code generation?",
    answer: "No limits whatsoever. Generate as many QR codes as you need, whenever you need them. No daily limits, no premium tiers, completely free forever."
  },
  {
    question: "What file formats can I download?",
    answer: "You can download your QR codes in multiple formats: high-resolution PNG for digital use, scalable SVG for web applications, and print-ready PDF for physical materials."
  },
  {
    question: "Can I customize the appearance of my QR code?",
    answer: "Yes! You can customize colors, add your logo, adjust the size, and create branded QR codes that match your business identity."
  },
  {
    question: "Will this work with all UPI apps?",
    answer: "Yes, our QR codes are compatible with all major UPI apps including PhonePe, Google Pay, Paytm, BHIM, and any other UPI-enabled application."
  },
  {
    question: "Can I use this for my business?",
    answer: "Absolutely! Our QR codes are perfect for businesses of all sizes. You can create branded QR codes for your shop, restaurant, online store, or any business that accepts UPI payments."
  },
  {
    question: "How do I display my QR code?",
    answer: "You can print your QR code and display it at your payment counter, add it to your website, include it in invoices, or share it digitally. The high-resolution output ensures it looks great everywhere."
  },
  {
    question: "What if someone scans my QR code by mistake?",
    answer: "UPI transactions require explicit confirmation from the payer. Even if someone scans your QR code, they must manually confirm the payment in their UPI app, so accidental payments are not possible."
  },
  {
    question: "Can I create QR codes for different amounts?",
    answer: "Yes, you can create multiple QR codes with different preset amounts. This is useful for businesses with fixed-price items or services."
  },
  {
    question: "Is there a mobile app?",
    answer: "No need for an app! Our web-based generator works perfectly on all devices - phones, tablets, and computers. It's optimized for mobile use and works offline once loaded."
  },
  {
    question: "How long does it take to generate a QR code?",
    answer: "QR codes are generated instantly as you type. There's no waiting time - you'll see your QR code update in real-time as you enter your details."
  },
  {
    question: "Can I edit a QR code after creating it?",
    answer: "QR codes themselves cannot be edited once generated. However, you can quickly create a new QR code with updated information using our generator anytime."
  },
  {
    question: "What information do I need to create a UPI QR code?",
    answer: "You only need your UPI ID (like yourname@paytm). Everything else - merchant name, amount, and note - is optional but recommended for better user experience."
  },
  {
    question: "Are there any ads or watermarks?",
    answer: "No ads, no watermarks, no branding on your QR codes. What you generate is completely clean and professional, ready for any use."
  }
];

export default function FAQPage() {
  return (
    <>
      <NetworkStatus />
      <PerformanceMonitor />

      {/* FAQPage Schema Markup */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqData.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          })
        }}
      />

      <div className="min-h-screen bg-background">
        <Header />
        
        <main className="mobile-container mobile-section">
          {/* Hero Section */}
          <section className="text-center space-y-6 mb-16">
            <div className="space-y-4">
              <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground">
                Frequently Asked Questions
              </h1>
              <p className="text-lg sm:text-xl text-foreground-secondary max-w-3xl mx-auto">
                Everything you need to know about creating and using UPI QR codes with our free generator.
              </p>
            </div>
          </section>

          {/* FAQ Section */}
          <section className="mb-16">
            <div className="max-w-4xl mx-auto">
              <Accordion type="single" collapsible className="space-y-4">
                {faqData.map((faq, index) => (
                  <AccordionItem 
                    key={index} 
                    value={`item-${index}`}
                    className="bg-card border rounded-lg px-6"
                  >
                    <AccordionTrigger className="text-left hover:no-underline py-6">
                      <span className="font-semibold">{faq.question}</span>
                    </AccordionTrigger>
                    <AccordionContent className="pb-6 text-foreground-secondary">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          </section>

          {/* Still Have Questions Section */}
          <section className="mb-16">
            <div className="bg-gradient-to-r from-primary/5 to-secondary/5 rounded-2xl p-8 md:p-12 text-center">
              <div className="max-w-2xl mx-auto space-y-6">
                <h2 className="text-2xl sm:text-3xl font-bold">
                  Still Have Questions?
                </h2>
                <p className="text-lg text-foreground-secondary">
                  Can't find what you're looking for? Try our UPI QR code generator - it's intuitive and easy to use.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Link 
                    href="/upi-qr-code-generator"
                    className="inline-flex items-center justify-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors"
                  >
                    Try the Generator
                  </Link>
                  <Link 
                    href="/contact"
                    className="inline-flex items-center justify-center gap-2 bg-card text-foreground border px-6 py-3 rounded-lg font-semibold hover:bg-muted transition-colors"
                  >
                    Contact Support
                  </Link>
                </div>
              </div>
            </div>
          </section>

          {/* Quick Tips Section */}
          <section className="mb-16">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-2xl sm:text-3xl font-bold text-center mb-8">
                Quick Tips for Success
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-card p-6 rounded-lg border">
                  <h3 className="font-semibold mb-3 text-success">✓ Best Practices</h3>
                  <ul className="space-y-2 text-sm text-foreground-secondary">
                    <li>• Always test your QR code before using it publicly</li>
                    <li>• Include your business name for better recognition</li>
                    <li>• Use high contrast colors for better scanning</li>
                    <li>• Print at least 2cm x 2cm for physical displays</li>
                  </ul>
                </div>
                <div className="bg-card p-6 rounded-lg border">
                  <h3 className="font-semibold mb-3 text-warning">⚠ Common Mistakes</h3>
                  <ul className="space-y-2 text-sm text-foreground-secondary">
                    <li>• Don't use very light colors that are hard to scan</li>
                    <li>• Avoid making QR codes too small for the display distance</li>
                    <li>• Don't forget to verify your UPI ID is correct</li>
                    <li>• Avoid placing QR codes on reflective surfaces</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>
        </main>

        <Footer />
      </div>
    </>
  );
}
